<?
$arr_estado[] = array("AC","Acre",1);
$arr_estado[] = array("AL","Alagoas",2);
$arr_estado[] = array("AM","Amazonas",3);
$arr_estado[] = array("AP","Amapá",4);
$arr_estado[] = array("BA","Bahia",5);
$arr_estado[] = array("CE","Ceará",6);
$arr_estado[] = array("DF","Distrito Federal",7);
$arr_estado[] = array("ES","Espírito Santo",8);
$arr_estado[] = array("GO","Goiás",9);
$arr_estado[] = array("MA","Maranhão",10);
$arr_estado[] = array("MG","Minas Gerais",11);
$arr_estado[] = array("MS","Mato Grosso do Sul",12);
$arr_estado[] = array("MT","Mato Grosso",13);
$arr_estado[] = array("PA","Pará",14);
$arr_estado[] = array("PB","Paraíba",15);
$arr_estado[] = array("PE","Pernambuco",16);
$arr_estado[] = array("PI","Piauí",17);
$arr_estado[] = array("PR","Paraná",18);
$arr_estado[] = array("RJ","Rio de Janeiro",19);
$arr_estado[] = array("RN","Rio Grande do Norte",20);
$arr_estado[] = array("RO","Rondônia",21);
$arr_estado[] = array("RR","Roraima",22);
$arr_estado[] = array("RS","Rio Grande do Sul",23);
$arr_estado[] = array("SC","Santa Catarina",24);
$arr_estado[] = array("SE","Sergipe",25);
$arr_estado[] = array("SP","São Paulo",26);
$arr_estado[] = array("TO","Tocantins",27);
?>